version: "3"

services:
  api:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - 8000:8000
    volumes:
      - ./app:/src
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  # redis:
  #   image: redis:6.0.6-alpine
  #   container_name: redis_db
  #   environment:
  #     - LANG=C.UTF-8
  #   ports:
  #     - 6380:6379
